### ISSUE TITLE
Замечания из первого проекта

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/range-slider#1]
Применить замечания из первого проекта.
+ добавить в README.md ссылку на пример работы слайдера.

**Comment by fatfutor** [comment]
Нужно ли приватным методам прописывать _ ?

**Comment by fatfutor** [comment]
можно ли использовать стиль именования обработчиков onElementEvent вместо handleEl...

**Comment by EvgeniyChuprov** [comment]
`Нужно ли приватным методам прописывать _ ?`
Нет. Это только для js, т.к. у него нет приватных методов.
`можно ли использовать стиль именования обработчиков onElementEvent вместо `
Поидее главное следовать требованию - 
`Именование:
Имя метода должно быть self descriptive(описывать само себя). Из названия должно быть понятно для чего нужен метод и что он делает. Не должно быть причин задумываться о его внутренней реализации.`
а handle - как раз переводится как  обработать
