### ISSUE TITLE
Ошибка при запуске.

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/range-slider#2]
При попытке запуска проекта, он падает с ошибкой:
![Снимок экрана от 2020-01-30 14-37-53](https://user-images.githubusercontent.com/36810364/73446646-2a198300-436e-11ea-8a8f-ea269f1bab9a.png)

**Comment by fatfutor** [comment]
> При попытке запуска проекта, он падает с ошибкой:
> ![Снимок экрана от 2020-01-30 14-37-53](https://user-images.githubusercontent.com/36810364/73446646-2a198300-436e-11ea-8a8f-ea269f1bab9a.png)

не знаю в чем дело =( у меня винда 10 (64)
не помню чтобы что-то глобально ставил, проект не падает. клонировал с гитхаб, все ок

**Comment by fatfutor** [comment]
переписал интерфейс Line, дал имя ILine.  если ошибка сместится ниже строкой, то я примерно понял как ее решить

**Comment by EvgeniyChuprov** [comment]
Ошибка та же самая, ничего не изменилось.

**Comment by EvgeniyChuprov** [comment]
Проверил под win 10 там работает.
Под linux заработало после того как поменял местами Line и Input.
![Снимок экрана от 2020-02-03 13-19-41](https://user-images.githubusercontent.com/36810364/73645190-e3869a00-4687-11ea-95ee-6703e43b18e0.png)

**Comment by fatfutor** [comment]
Поменял местами Line и Input
